version: "3"
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql_container
    networks:
      - my_network
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: mydatabase
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: phpmyadmin_container
    networks:
      - my_network
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data:
